version: "3"

services:
  web:
    #image: frontend_web
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - reactjs-data-volume:/app
    stdin_open: true

volumes:
  reactjs-data-volume:
