language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t ankursingh3/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ankursingh3/docker-react npm run test -- --coverage
